config {
  type: "incremental",
  schema: "dataset",
  name: "STD_OPF_VALE_VISTA",
  bigquery: {
    partitionBy: "DATE(FEC_INGESTA)"
  },
  assertions: {
    //uniqueKey: ["SUCUR_EMI", "NUMERO"],
    nonNull: ["FEC_INGESTA", "RUT_BENEFICIA", "VALOR", "NUMERO"]
  }
}

SELECT
  *
FROM ${ref("HIST_OPF_VALE_VISTA")}

${when(incremental(), 
  `WHERE FEC_INGESTA > (SELECT MAX(FEC_INGESTA) FROM ${self()})` 
)}
