config {
  type: "incremental",
  schema: constants.DEST_STD,
  name: "STD_OPF_VALE_VISTA",
  bigquery: {
    partitionBy: "DATE(FEC_INGESTA)"
  },
  assertions: {
    //uniqueKey: ["SUCUR_EMI", "NUMERO"],
    nonNull: ["FEC_INGESTA", "RUT_BENEFICIA", "VALOR", "NUMERO"]
  }
}

SELECT
  *
FROM ${ref({ schema: constants.DEST_RAW_DIARIA, name: "RAW_DIARIA_OPF_VALE_VISTA" })}
WHERE DATE(FEC_INGESTA) = DATE("${constants.FECHA_EJE}")
