config {
  type: "incremental",
  schema: "cst_banking",
  name: "MPLUS_101_2_TXT",
  tags: ["MPLUS_101_2_TXT_consumo_cst", "cst"],
  bigquery: {
    partitionBy: "FECHA_PROCESO"
  }
}

-- Parte 1: maestro
SELECT *
FROM `${dataform.projectConfig.defaultDatabase}.std_banking.OPF_CASA_TXN`
WHERE CAST(FECHA_PROCESO AS DATE) = DATE('${dataform.projectConfig.vars.process_date}')

${when(dataform.projectConfig.vars.interface_enabled !== "false", `
UNION ALL

-- Parte 2: interfaz on-premise estandarizada (solo si interface_enabled != false)
SELECT *
FROM ${ref("STD_MPLUS_101_2_TXT")}
WHERE FECHA_PROCESO = DATE('${dataform.projectConfig.vars.process_date}')
`)}
