
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_TasasPromedio_SEMANA_Banco",
    tags: ["TasasPromedio_SEMANA_Banco_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_TasasPromedio_SEMANA_Banco_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
