
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_CVISAL_%(H_)_CTRL",
    tags: ["CVISAL_%(H_)_CTRL_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_CVISAL_%(H_)_CTRL_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
