config {
  type: "table",
  schema: constants.DEST_STD,
  name: "STD_LGSOPERACIONESME",
  bigquery: {
    partitionBy: "DATE(FECHA_PROCESO)"
  },
  assertions: {
    uniqueKey: ["CUENTA"],
    nonNull: ["FECHA_PROCESO", "RUT_TIT", "CUENTA"]
  }
}

SELECT
  FECHA_PROCESO,
  RUT_TIT,
  CUENTA,
  AC_OPEN_DT,
  AC_CLOSE_DT,
  MOCIERM,
  OFICINA,
  MONEDA

FROM ${ref("MAESTRO_CUENTAS")}
WHERE MONEDA = 3