
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_BLOQUEO_TODO_TEF_B_PAS_csv",
    tags: ["BLOQUEO_TODO_TEF_B_PAS_csv_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_BLOQUEO_TODO_TEF_B_PAS_csv_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
