
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_LGSOPERACIONESMX",
    tags: ["LGSOPERACIONESMX_std", "std"],
    
  uniqueKey: ["NUMRUT", "CUENTA"],
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
    assertions: {
        
  uniqueKey: ["NUMRUT", "CUENTA"],
    }
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    NUMRUT,
		DIGRUT,
		CODIGO,
		SAFE_CAST(FECHA_INI AS NUMERIC) AS FECHA_INI,
		SAFE_CAST(FECHA_TER AS NUMERIC) AS FECHA_TER,
		CAUSA_CIE,
		SAFE_CAST(SUCURSAL AS NUMERIC) AS SUCURSAL
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_LGSOPERACIONESMX_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
