
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_C028P",
    tags: ["C028P_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_C028P_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
