
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_00101AUX_IDX",
    tags: ["00101AUX_IDX_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_00101AUX_IDX_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
