
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_AVISO_BLOQUEO_MP_TD_CSV",
    tags: ["AVISO_BLOQUEO_MP_TD_CSV_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    rutnls,
		Cust_Ac_No,
		value_date,
		diff_DIA,
		account_class,
		AC_CCY,
		nombre_cliente,
		DireccionParticular,
		ComunaParticular,
		CiudadParticular,
		RegionParticular,
		email
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_AVISO_BLOQUEO_MP_TD_CSV_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
