
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_CTA_BIA_FCC_Descarga0zzzz_DAT",
    tags: ["CTA_BIA_FCC_Descarga0zzzz_DAT_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_CTA_BIA_FCC_Descarga0zzzz_DAT_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
