config {
  type: "incremental",
  schema: "cst_banking",
  name: "D1028_csv",
  tags: ["D1028_csv_consumo_cst", "cst"],
  bigquery: {
    partitionBy: "FECHA_PROCESO"
  }
}

-- Parte 1: maestro
SELECT *
FROM `${dataform.projectConfig.defaultDatabase}.std_banking.OPF_CASA_MAS,OPF_CASA_TXN`
WHERE CAST(FECHA_PROCESO AS DATE) = DATE('${dataform.projectConfig.vars.process_date}')

${when(dataform.projectConfig.vars.interface_enabled !== "false", `
UNION ALL

-- Parte 2: interfaz on-premise estandarizada (solo si interface_enabled != false)
SELECT *
FROM ${ref("STD_D1028_csv")}
WHERE FECHA_PROCESO = DATE('${dataform.projectConfig.vars.process_date}')
`)}
