
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_ONP_a_BO",
    tags: ["ONP_a_BO_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_ONP_a_BO_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
