
config {
    type: "incremental",
    schema: constants.DEST_STD,
    name: "STD_D1028_csv",
    tags: ["D1028_csv_std", "std"],
    
    bigquery: {
        partitionBy: "FECHA_PROCESO"
     },
    
}
SELECT
    CAST(load_date AS DATE) AS FECHA_PROCESO,
    
FROM `${dataform.projectConfig.defaultDatabase}.raw_banking.raw_D1028_csv_daily`
WHERE load_date = DATE('${dataform.projectConfig.vars.process_date}')
